####################################################
#                                                  #
#                 STATS & DATA                     #
#                                                  #
####################################################

title: Stats & Data
icon: mdi:train
cards:
  - type: entities
    title: Adam's & Wabash Bus Times
    show_header_toggle: false
    entities:
      - type: section
        label: Route 151
      - entity: automation.update_route_151
        name: Update?
        icon: mdi:update
      - entity: sensor.151first
        name: First
        icon: mdi:bus-clock
      - entity: sensor.151second
        name: Second
        icon: mdi:bus-clock
      - type: section
        label: Route 126
      - entity: automation.update_route_126
        name: Update?
        icon: mdi:update
      - entity: sensor.126first
        name: First
        icon: mdi:bus-clock
      - entity: sensor.126second
        name: Second
        icon: mdi:bus-clock
      - type: section
        label: Route 28
      - entity: automation.update_route_28
        name: Update?
        icon: mdi:update
      - entity: sensor.28first
        name: First
        icon: mdi:bus-clock
      - entity: sensor.28second
        name: Second
        icon: mdi:bus-clock
      - type: section
        label: Route 7
      - entity: automation.update_route_7
        name: Update?
        icon: mdi:update
      - entity: sensor.7first
        name: First
        icon: mdi:bus-clock
      - entity: sensor.7second
        name: Second
        icon: mdi:bus-clock
  - type: entities
    show_header_toggle: false
    title: Metra Information
    entities:
      - type: weblink
        url: 'https://metrarail.com/maps-schedules/train-lines/md-w'
        name: Milwaukee District West Scheudle
        icon: 'mdi:map-clock-outline'
      - type: section
        label: Bartlett to Union Station
      - entity: sensor.bartlett_to_union
        name: Next Train Departs
      - entity: sensor.next_b_to_u_depart
        name: Departs
        icon: 'mdi:calendar-clock'
      - entity: sensor.next_b_to_u_arrival
        name: Arrives
        icon: 'mdi:calendar-clock'
      - type: section
        label: Union Station to Bartlett
      - entity: sensor.union_to_bartlett
        name: Next Train Departs
      - entity: sensor.next_u_to_b_depart
        name: Departs
        icon: 'mdi:calendar-clock'
      - entity: sensor.next_u_to_b_arrival
        name: Arrives
        icon: 'mdi:calendar-clock'


####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
