####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 223
  unit_system: imperial
  time_zone: !secret time_zone

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

#https://home-assistant.io/components/mqtt_statestream/
mqtt_statestream:
  base_topic: remote

#https://home-assistant.io/components/mqtt/
mqtt:
  broker: 192.168.1.24
  port: 1883
  client_id: home-assistant-2
  username: !secret mqttusername
  password: !secret mqttpassword

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://home-assistant.io/components/frontend/
frontend:

####################################################
#                                                  #
#                 BINARY SENSORS                   #
#                                                  #
####################################################

#https://home-assistant.io/components/binary_sensor.rpi_gpio/
binary_sensor:
  - platform: rpi_gpio
    ports:
      22: Motion

####################################################
#                                                  #
#                     SENSORS                      #
#                                                  #
####################################################

#https://home-assistant.io/components/sensor.dht/
sensor:
  platform: dht
  sensor: DHT22
  pin: 4
  monitored_conditions:
    - temperature
    - humidity

####################################################
#                                                  #
#                      SWITCH                      #
#                                                  #
####################################################

#https://home-assistant.io/components/switch.rpi_gpio/
switch:
  - platform: rpi_gpio
    ports:
      23: Relay 1
      24: Relay 2

#https://home-assistant.io/components/switch.rpi_rf/
#  - platform: rpi_rf
#    gpio: 17
#    switches:
#     rfswitch1:
#       code_on: 267571
#       code_off: 267580
#       protocol: 1
#       pulselength: 194
#       signal_repetitions: 20
#     rfswitch2:
#       code_on: 267715
#       code_off: 267724
#       protocol: 1
#       pulselength: 194
#       signal_repetitions: 20
#     rfswitch3:
#       code_on: 268035
#       code_off: 268044
#       protocol: 1
#       pulselength: 194
#       signal_repetitions: 20
#     rfswitch4:
#       code_on: 269571
#       code_off: 269580
#       protocol: 1
#       pulselength: 194
#       signal_repetitions: 20
#     rfswitch5:
#       code_on: 275715
#       code_off: 275724
#       protocol: 1
#       pulselength: 194
#       signal_repetitions: 20

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
