####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize/
  whitelist_external_dirs:
    - /config
####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/frontend/
frontend:
  javascript_version: latest

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 2

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/components/map/
map:

#https://home-assistant.io/components/sun/
sun:

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
zone: !include zones.yaml

####################################################
#                                                  #
#                     DUCKDNS                      #
#                                                  #
####################################################

#https://home-assistant.io/components/duckdns/
duckdns:
  domain: !secret domain
  access_token: !secret access_token

####################################################
#                                                  #
#               EMULATED HUE                       #
#                                                  #
####################################################

#https://home-assistant.io/components/emulated_hue/
emulated_hue:
  host_ip: 192.168.1.24
  exposed_domains:
    - light
    - switch

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

#https://home-assistant.io/docs/mqtt/broker/#run-your-own
mqtt:
  broker: 192.168.1.24
  port: 1883
  client_id: home-assistant-1

####################################################
#                                                  #
#                      NEST                        #
#                                                  #
####################################################

#https://home-assistant.io/components/nest/
nest:
  client_id: !secret client_id
  client_secret: secret client_secret

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                                                  #
#                     ZWAVE                        #
#                                                  #
####################################################

#https://home-assistant.io/docs/z-wave/
zwave:
 usb_path: /dev/ttyACM0

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
