####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/climate/
climate:
  - platform: zwave

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/downloader/
downloader:
  download_dir: /share

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 2
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks: 192.168.1.0/24

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://www.home-assistant.io/components/map/
map:

#https://home-assistant.io/components/sun/
sun:

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
zone: !include zones.yaml

####################################################
#                                                  #
#               EMULATED HUE                       #
#                                                  #
####################################################

#https://home-assistant.io/components/emulated_hue/
emulated_hue:
  expose_by_default: false
  entities:
    light.yeelightrgb2:
      hidden: false
      name: Notification
    switch.basic1:
      name: Lamps
      hidden: false
    switch.receiverpower:
      hidden: false
      name: Amplifier
    switch.tvpower:
      hidden: false
      name: TV
    script.music:
      hidden: false
      name: Music
    script.normallight:
      hidden: false
      name: normal light
    script.volumedown:
      hidden: false
      name: Volume Down
    script.volumeup:
      hidden: false
      name: Volume Up
    script.fire_tv:
      hidden: false
      name: Fire TV
    script.findadamsiphone:
      hidden: false
      name: findadamsiphone
    script.findamysiphone:
      hidden: false
      name: findamysiphone

####################################################
#                                                  #
#                    GROUP                         #
#                                                  #
####################################################

#https://www.home-assistant.io/components/group/
group:
  outside_lights:
    - light.yeelight1
    - light.yeelight2
    - light.yeelight3
    - light.yeelight4

####################################################
#                                                  #
#                    MEDIA PLAYER                  #
#                                                  #
####################################################

#https://www.home-assistant.io/components/media_player.firetv/
media_player:
  platform: firetv
  name: Fire TV
  host: 192.168.1.21
  adbkey: /config/android/adbkey
  get_sources: false
  get_source: false

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

#https://home-assistant.io/docs/mqtt/broker/#run-your-own
# mqtt:
#   broker: 192.168.1.24
#   port: 1883
#   client_id: home-assistant-1
#   username: !secret mqttun
#   password: !secret mqttpw

####################################################
#                                                  #
#                   OPEN GARAGE                    #
#                                                  #
####################################################

#https://home-assistant.io/components/cover.opengarage/
cover:
  - platform: opengarage
    covers:
      garage:
        host:  192.168.1.18
        device_key: !secret device_key
        name:  Garage Door

####################################################
#                                                  #
#                REST COMMAND                      #
#                                                  #
####################################################

rest_command:
  google_backup:
    url: 'http://192.168.1.24:8055/gb/doBackup'
    timeout: '300'

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky

####################################################
#                                                  #
#                     ZWAVE                        #
#                                                  #
####################################################

#https://home-assistant.io/docs/z-wave/
zwave:
 usb_path: /dev/ttyACM0
 device_config_glob:
   "binary_sensor.**":
     ignored: true
   "sensor.*_alarm_type*":
     ignored: true
   "sensor.*_sourcenodeid*":
     ignored: true
   "sensor.vision_zg8101_garage_door_detector_burglar":
     ignored: true
   "sensor.unknown_id021f_unknown_type0003_id0101_alarm_level":
     ignored: true
   "sensor.ge_32563_hinge_pin_smart_door_sensor_alarm_level":
     ignored: true
   "sensor.ge_32563_hinge_pin_smart_door_sensor_alarm_level_2":
     ignored: true

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
