####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/frontend/
frontend:
  javascript_version: latest

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  api_password: !secret api_password
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 2
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/components/map/
map:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/hassio/
hassio:

#https://www.home-assistant.io/components/downloader/
downloader:
  download_dir: /share

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
zone: !include zones.yaml

####################################################
#                                                  #
#               EMULATED HUE                       #
#                                                  #
####################################################

#https://home-assistant.io/components/emulated_hue/
emulated_hue:
  expose_by_default: false
  entities:
    light.yeelightrgb2:
      hidden: false
      name: Notification
    switch.basic1:
      name: Lamps
      hidden: false
    switch.receiverpower:
      hidden: false
      name: Amplifier
    switch.tvpower:
      hidden: false
      name: TV
    script.music:
      hidden: false
      name: Music
    script.normallight:
      hidden: false
      name: normal light
    script.volumedown:
      hidden: false
      name: Volume Down
    script.volumeup:
      hidden: false
      name: Volume Up
    switch.htpc_switch:
      hidden: false
      name: computer

####################################################
#                                                  #
#                     GROUP                        #
#                                                  #
####################################################

#https://home-assistant.io/components/group
group:
  Outside Lights:
    - light.yeelight1
    - light.yeelight3
    - light.yeelight2
    - light.yeelight4

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

#https://home-assistant.io/docs/mqtt/broker/#run-your-own
mqtt:
  broker: 192.168.1.24
  port: 1883
  client_id: home-assistant-1

####################################################
#                                                  #
#                      NEST                        #
#                                                  #
####################################################

#https://home-assistant.io/components/nest/
nest:
  client_id: !secret client_id
  client_secret: secret client_secret

####################################################
#                                                  #
#                PANEL CUSTOM                      #
#                                                  #
####################################################

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

#https://www.home-assistant.io/components/weather.yweather/
weather:
  - platform: yweather
    woeid: !secret woeid

####################################################
#                                                  #
#                     ZWAVE                        #
#                                                  #
####################################################

#https://home-assistant.io/docs/z-wave/
zwave:
 usb_path: /dev/ttyACM0

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
