####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/climate/
climate:
  - platform: zwave

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/opengarage/
cover:
  platform: opengarage
  covers:
      garage:
        host:  192.168.1.18
        device_key: !secret device_key
        name: Garage Door

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  ip_ban_enabled: true
  login_attempts_threshold: 2

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
frontend: !include frontend.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
zone: !include zones.yaml

####################################################
#                                                  #
#               GOOGLE ACTIONS                     #
#                                                  #
####################################################
#https://www.home-assistant.io/integrations/cloud/
cloud:
#https://www.nabucasa.com/config/google_assistant/
  google_actions:
    filter:
      include_entities:
        - group.living_room_lamps
        - input_boolean.guest
        - script.volumedown
        - script.volumeup
        - input_boolean.feeddog
        - script.normallight
        - switch.cast
        - switch.receiverpower
        - switch.tvpower
    entity_config:
      group.living_room_lamps:
        name: Living Room Lamps
        aliases: Lamps
        room: Family Room
      input_boolean.guest:
        name: Guest Mode
        aliases: Guest
        room: Family Room
      switch.cast:
        name: Cast
        aliases: Cast Google Home
        room: Family Room
      script.volumedown:
        name: Volume Down
        room: Family Room
      script.volumeup:
        name: Volume Up
        room: Family Room
      light.yeelightrgb2:
        name: Notification light
        aliases: Corner Light
        room: Family Room
      input_boolean.feeddog:
        name: Feed The Dog
        aliases:
          - I fed the Dog
          - Dog fed
          - fed dog
        room: Family Room
      script.normallight:
        name: Normal Light
        aliases: Normal Lamp
        room: Family Room
      switch.receiverpower:
        name: Receiver Power
        aliases:
          - Receiver
          - Amplifier
          - Amp
        room: Family Room
      switch.tvpower:
        name: TV Power
        aliases:
          - TV
          - Television
        room: Family Room

####################################################
#                                                  #
#                    GROUP                         #
#                                                  #
####################################################

#https://www.home-assistant.io/components/group/
group:
  outside_lights:
    - light.yeelight1
    - light.yeelight2
    - light.yeelight3
    - light.yeelight4
  front_lights:
    - light.yeelight1
    - light.yeelight3
    - light.yeelight4
  adam_home_presence:
    - device_tracker.adams_iphone #GPS
    - device_tracker.adam_s_iphone #WiFi
  amy_home_presence:
    - device_tracker.amys_iphone #GPS
    - device_tracker.amy_s_iphone #WiFi
  home_presence:
    - device_tracker.adams_iphone #GPS
    - device_tracker.adam_s_iphone #WiFi
    - device_tracker.amys_iphone #GPS
    - device_tracker.amy_s_iphone #WiFi
  living_room_lamps:
    - switch.basic1
    - light.yeelightrgb2

####################################################
#                                                  #
#                   SPEETEST                       #
#                                                  #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 1776
  monitored_conditions:
    - download
    - upload

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

####################################################
#                                                  #
#                     YEELIGHTS                    #
#                                                  #
####################################################

#https://home-assistant.io/components/light.yeelight/
yeelight:
  devices:
    192.168.1.10:
      name: Yeelight1
    192.168.1.11:
      name: Yeelight2
    192.168.1.12:
      name: Yeelight3
    192.168.1.26:
      name: Yeelight4
    192.168.1.28:
      name: Yeelight5
    192.168.1.25:
      name: YeelightRGB2

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
