####################################################
#                                                  #
#                   RESOURCES                      #
#                                                  #
####################################################

resources:
  #https://github.com/custom-cards/tracker-card
  - url: /local/tracker-card.js?v=0.2.0
    type: js
  #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?v=297fcc
    type: js
  #https://github.com/MizterB/lovelace-secondaryinfo-entity-row
  - url: /local/secondaryinfo-entity-row.js?v=0.1
    type: module
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js?v=v0.1.0
    type: js

title: Home
#background: center / cover no-repeat url("/local/background2.jpg") fixed
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/devicestatus.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/switches.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/statsndata.yaml

####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
