####################################################
#                                                  #
#                   LOVELACE                       #
#                                                  #
####################################################

resources:
  #https://github.com/MizterB/lovelace-secondaryinfo-entity-row
  - url: /local/secondaryinfo-entity-row.js
    type: module
  #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?v=9
    type: js
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js
    type: js
  #https://github.com/maykar/custom-header
  - url: /local/custom-header.js
    type: module

custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  shadow: on
  chevrons: false

title: Home
background: var(--background-image)
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/switches.yaml
  - !include lovelace/devicestatus.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/data.yaml
  - !include lovelace/googlehomehub.yaml

####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
