####################################################
#                                                  #
#                   RESOURCES                      #
#                                                  #
####################################################

resources:
  #https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/slider-entity-row.js?v=ba8f50
    type: js
  #https://github.com/custom-cards/tracker-card
  - url: /local/tracker-card.js?v=0.1.5
    type: js
title: Home
background: center / cover no-repeat url("/local/background2.jpg") fixed
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/devicestatus.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/switches.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/statsndata.yaml

####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
