####################################################
#                                                  #
#                   RESOURCES                      #
#                                                  #
####################################################

resources:
  #https://github.com/custom-cards/tracker-card
  - url: /local/tracker-card.js?v=1.2.5
    type: js
  #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?v=deb8e3
    type: js
  #https://github.com/MizterB/lovelace-secondaryinfo-entity-row
  - url: /local/secondaryinfo-entity-row.js?v=0.1
    type: module
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js?v=v0.1.1
    type: js
  #https://github.com/kalkih/mini-graph-card
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module

title: Home
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/switches.yaml
  - !include lovelace/devicestatus.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/statsndata.yaml
  - !include lovelace/automations.yaml

####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
