
#########################################################
#                                                       #
#        INTERIOR GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Interior Garage Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor2
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('group.adam_home_presence') != 'home' }}"
        - condition: template
          value_template: "{{ states('group.amy_home_presence') != 'home' }}"
    action:
      - service: notify.ios_adams_iphone
        data:
          title: "Interior Garage Door Opened"
          message: "The Interior Garage Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.garagedoorstatus
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('group.adam_home_presence') != 'home' }}"
        - condition: template
          value_template: "{{ states('group.amy_home_presence') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Exterior Garage Door Opened"
        message: "The Exterior Garage Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#              FRONT DOOR OPENED AND AWAY               #
#                                                       #
#########################################################

  - alias: "Front Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor1
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('group.adam_home_presence') != 'home' }}"
        - condition: template
          value_template: "{{ states('group.amy_home_presence') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Front Door Opened"
        message: "The Front door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Left Open When Away"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'leave'
      - platform: zone
        entity_id: device_tracker.amy_siphone
        zone: zone.home
        event: 'leave'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adams_iphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amys_iphone') != 'home' }}"
        - condition: state
          entity_id: sensor.garagedoorstatus
          state: 'Open'
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Exterior Garage Door Left Open"
        message: "The Exterior Garage Door was left open and Amy and Adam are not home"

#########################################################
#                                                       #
#              BACK DOOR OPENED AND AWAY                #
#                                                       #
#########################################################

  - alias: "Back Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.backdoorstatus
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('group.adam_home_presence') != 'home' }}"
        - condition: template
          value_template: "{{ states('group.amy_home_presence') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Back Door Opened"
        message: "The Back Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#               DOORBELL PESSED NOTIFICATION            #
#                                                       #
#########################################################

  - alias: "Doorbell Pressed"
    trigger:
      platform: state
      entity_id: sensor.doorbell
    condition:
      condition: template
      value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
    action:
      - service: notify.alexa_media
        data:
          target:
            - media_player.adam_s_echo_dot
          data:
            type: announce
          message: "Someone is at the front door!"
      - service: notify.ios_adams_iphone
        data:
          title: "Doorbell Pressed"
          message: "The doorbell was pressed"
      - service_template: >-
          {%- if is_state('light.yeelightrgb2' , 'off') -%}
            input_boolean.turn_off
          {%- else -%}
            input_boolean.turn_on
          {%- endif -%}
        entity_id: input_boolean.doorbelllight
      - service: light.turn_on
        entity_id: light.yeelightrgb2
        data:
          effect: 'Fast Random Loop'
      - delay: '00:00:02'
      - service: light.turn_on
        entity_id: light.yeelightrgb2
        data:
          effect: Stop
      - service_template: >-
          {%- if is_state('input_boolean.doorbelllight' , 'off') -%}
            light.turn_off
          {%- else -%}
            light.turn_on
          {%- endif -%}
        entity_id: light.yeelightrgb2

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
