
#########################################################
#                                                       #
#        INTERIOR GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Interior Garage Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor2
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amy_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79a4a851') != 'home' }}"
    action:
      - service: notify.ios_adams_iphone
        data:
          title: "Interior Garage Door Opened"
          message: "The Interior Garage Door was opened and Amy and Adam are not home"
      - service: homeassistant.turn_off
        entity_id: automation.interior_garage_door_opened_when_away
      - delay: '00:10:00'
      - service: homeassistant.turn_on
        entity_id: automation.interior_garage_door_opened_when_away

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.garagedoorstatus
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amy_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79a4a851') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Exterior Garage Door Opened"
        message: "The Exterior Garage Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#              FRONT DOOR OPENED AND AWAY               #
#                                                       #
#########################################################

  - alias: "Front Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor1
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amy_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79a4a851') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Front Door Opened"
        message: "The Front door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Left Open When Away"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'leave'
      - platform: zone
        entity_id: device_tracker.amy_siphone
        zone: zone.home
        event: 'leave'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amy_siphone') != 'home' }}"
        - condition: state
          entity_id: sensor.garagedoorstatus
          state: 'Open'
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Exterior Garage Door Left Open"
        message: "The Exterior Garage Door was left open and Amy and Adam are not home"

#########################################################
#                                                       #
#              BACK DOOR OPENED AND AWAY                #
#                                                       #
#########################################################

  - alias: "Back Door Opened When Away"
    trigger:
      platform: state
      entity_id: sensor.backdoorstatus
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.amy_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79a4a851') != 'home' }}"
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Back Door Opened"
        message: "The Back Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
