#########################################################
#                                                       #
#         NOTIFY DESKTOP PC TURNED ON AND AWAY          #
#                                                       #
#########################################################
#            [Validated 12/17/2018 - v 83.3]            #

  - alias: "DESKTOP PC ON WHEN AWAY"
    trigger:
      platform: state
      entity_id: switch.desktop_switch
      from: 'off'
      to: 'on'
    condition:
        condition: template
        value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
    action:
      service: notify.home_assistant
      data:
        title: "Desktop PC turned on"
        message: "Desktop PC was turned on and Adam is not home"

#########################################################
#                                                       #
#                 FAILED LOGIN ATTEMPTS                 #
#                                                       #
#########################################################
#            [Validated 12/10/2018 - v 83.3]            #

  - alias: "Send notification upon failed login attempt"
    trigger:
      - platform: state
        entity_id: persistent_notification.httplogin
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: notify.home_assistant
        data_template:
          title: "{{ states.persistent_notification.httplogin.attributes.message }}"
          message: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.httplogin.attributes.message.split ("from ") [1]}}'
      - service: persistent_notification.dismiss
        data:
          notification_id: 'httplogin'

#########################################################
#                                                       #
#           NOTIFY OF NEW DEVICE ON NETWORK             #
#                                                       #
#########################################################
#            [Validated 12/12/2018 - v 83.3]            #

  - alias: Notify If New Devices
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.home_assistant
        data_template:
          message: >
            New device:
            {{trigger.event.data.entity_id}}
          title: New device

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
