#########################################################
#                                                       #
#                   WEATHER ALERTS                      #
#                                                       #
#########################################################

- alias: Dupage NWS Notification Weather Alert
  trigger:
    platform: state
    entity_id: sensor.dupage_nws_alert_count
  condition:
    condition: template
    value_template: '{{states.sensor.dupage_nws_alert_count.state | int > 0}}'
  action:
    - service: notify.ios_adams_iphone
      data:
        title: Dupage County Weather Alert
        message: "The National Weather Service has issued a {{ states.sensor.dupage_nws_alert_event.state }} for your area. It expires at {{ as_timestamp(state_attr('sensor.dupage_nws_alert_event', 'features')[0].properties.expires)| timestamp_custom('%-I:%M %p on %-m-%-d-%Y') }}."

- alias: Cook NWS Notification Weather Alert
  trigger:
    platform: state
    entity_id: sensor.cook_nws_alert_count
  condition:
    condition: template
    value_template: '{{states.sensor.cook_nws_alert_count.state | int > 0}}'
  action:
    - service: notify.ios_adams_iphone
      data:
        title: Cook County Weather Alert
        message: "The National Weather Service has issued a {{ states.sensor.cook_nws_alert_event.state }} for your area. It expires at {{ as_timestamp(state_attr('sensor.cook_nws_alert_event', 'features')[0].properties.expires)| timestamp_custom('%-I:%M %p on %-m-%-d-%Y') }}."
#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
