#########################################################
#                                                       #
#                   WEATHER ALERTS                      #
#                                                       #
#########################################################

- alias: Dupage NWS Notification Weather Alert
  trigger:
    platform: state
    entity_id: sensor.dupage_nws_alert_count
  condition:
    condition: template
    value_template: '{{states.sensor.dupage_nws_alert_count.state | int > 0}}'
  action:
    - service: notify.ios_adams_iphone
      data_template:
        title: Dupage County Weather Alert
        message: "The National Weather Service has issued a {{ states.sensor.dupage_nws_alert_event.state }} for your area. It expires at {{ as_timestamp(state_attr('sensor.dupage_nws_alert_event', 'features')[0].properties.expires)| timestamp_custom('%-I:%M %p on %-m-%-d-%Y') }}."

- alias: Cook NWS Notification Weather Alert
  trigger:
    platform: state
    entity_id: sensor.cook_nws_alert_count
  condition:
    condition: template
    value_template: '{{states.sensor.cook_nws_alert_count.state | int > 0}}'
  action:
    - service: notify.ios_adams_iphone
      data_template:
        title: Cook County Weather Alert
        message: "The National Weather Service has issued a {{ states.sensor.cook_nws_alert_event.state }} for your area. It expires at {{ as_timestamp(state_attr('sensor.cook_nws_alert_event', 'features')[0].properties.expires)| timestamp_custom('%-I:%M %p on %-m-%-d-%Y') }}."

#########################################################
#                                                       #
#                   WEATHER UPDATE                      #
#                                                       #
#########################################################

- alias: Update Weather Sensors
  trigger:
      platform: time
      at: '00:00:01'
  action:
    - service: homeassistant.update_entity
      entity_id:
        - sensor.forecast_0
        - sensor.forecast_1
        - sensor.forecast_2
        - sensor.forecast_3
        - sensor.forecast_4
        - sensor.forecast_5
        - sensor.forecast_6
        - sensor.forecast_7
        - sensor.duedate

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
